version: "3.7"
services:
  client:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment: 
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes: 
      - ".:/usr/src/app"
